#!/usr/bin/env python
import sys
from os.path import dirname, realpath
sys.path.insert(1, dirname(realpath(__file__)))
from PyQt5.QtWidgets import QApplication
from sloth.core.labeltool import LabelTool
from sloth import APP_NAME, ORGANIZATION_NAME, ORGANIZATION_DOMAIN

import logging

LOG = logging.getLogger(__name__)
LOG.setLevel(logging.DEBUG)

handler = logging.FileHandler('logging.log')
handler.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
LOG.addHandler(handler)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setOrganizationName(ORGANIZATION_NAME)
    app.setOrganizationDomain(ORGANIZATION_DOMAIN)
    app.setApplicationName(APP_NAME)

    labeltool = LabelTool()
    labeltool.execute_from_commandline(sys.argv)

    sys.exit(app.exec_())
